# Ref: https://github.com/scipy/scipy/blob/main/.github/workflows/windows.yml

# Workflow to build and test wheels.
# To work on the wheel building infrastructure on a fork, comment out:
#
# if: github.repository == 'has2k1/scikit-misc'
#
# in the get_commit_message job include [wheel build] in your commit
# message to trigger the build. All files related to wheel building are located
# at tools/wheels/
name: Wheel Builder
on:
  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │  ┌───────────── hour (0 - 23)
  #        │  │ ┌───────────── day of the month (1 - 31)
  #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │  │ │ │ │
  - cron: "0  0 * * 6"
  push:
    tags:
      - v*
    branches:
      - wheels
  workflow_dispatch:

permissions:
   contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  parse_commit_info:
    name: Parse Commit Information
    runs-on: ubuntu-latest
    if: github.repository == 'has2k1/scikit-misc'
    outputs:
      can_build: ${{ steps.check_commit_message.outputs.can_build }}
      can_release: ${{ steps.check_tag.outputs.can_release }}
    steps:
      - name: Checkout scikit-misc
        uses: actions/checkout@v3
        # Gets the correct commit message for pull request
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check if Commit Message Tells Us to Build Wheels
        id: check_commit_message
        run: |
          set -xe
          COMMIT_MSG=$(git log --no-merges -1)
          RUN="No"
          if [[ "$COMMIT_MSG" == *"[wheel build]"* ]]; then
              RUN="Yes"
          fi
          echo "can_build=$RUN" >> $GITHUB_OUTPUT
          echo github.ref ${{ github.ref }}

      - name: Check If Tag is Releasible
        id: check_tag
        run: |
          set -xe
          # Yes or No
          CAN_RELEASE=$(python ./tools/github/can_release.py)
          echo "can_release=$CAN_RELEASE" >> $GITHUB_OUTPUT

  build_wheels:
    name: Build wheel for ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }} ${{ matrix.buildplat[2] }}
    needs: parse_commit_info

    if: >-
      contains(needs.parse_commit_info.outputs.can_build, 'Yes') ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.buildplat[0] }}

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
        # should also be able to do multi-archs on a single entry, e.g.
        # [windows-2019, win*, "AMD64 x86"]. However, those two require a different compiler setup
        # so easier to separate out here.
        - [ubuntu-20.04, manylinux, x86_64]

        # When the macos-10.15 image is retired the gfortran/openblas chain
        # may have to be reworked because the gfortran-4.9.0 compiler currently
        # used in CI doesn't work in the macos-11.0 image. This will require a more
        # recent gfortran (gfortran-9 is present on the macOS-11.0 image), and
        # will probably require that the prebuilt openBLAS is updated.
        # xref https://github.com/andyfaff/scipy/pull/28#issuecomment-1203496836
        - [macos-10.15, macosx, x86_64]
        - [windows-2019, win, AMD64]

        python: [["cp38", "3.8"], ["cp39", "3.9"], ["cp310", "3.10"], ["cp311", "3.11"]]
        # python[0] is used to specify the python versions made by cibuildwheel

    env:
      IS_32_BIT: ${{ matrix.buildplat[2] == 'x86' }}
      # upload to staging if it's a push to a maintenance branch and the last
      # commit message contains '[wheel build]'
      IS_PUSH: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/wheels') && contains(needs.parse_commit_info.outputs.can_build, 'Yes') }}
      IS_SCHEDULE_DISPATCH: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout scikit-misc
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.8

      - name: win_amd64 - install rtools
        if: ${{ runner.os == 'Windows' && env.IS_32_BIT == 'false' }}
        run: |
          # mingw-w64
          choco install rtools --no-progress
          echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH

#      - name: win32 - configure mingw for 32-bit builds
#        if: ${{ runner.os == 'Windows' && env.IS_32_BIT == 'true' }}
#        run: |
#          # taken from numpy wheels.yml script
#          # Force 32-bit mingw. v 8.1.0 is the current version used to build
#          # the 32 bit openBLAS library (not sure if that matters)
#          choco uninstall mingw
#          choco install -y mingw --forcex86 --force --version=8.1.0
#          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin;" >> $env:GITHUB_PATH
#          echo $(gfortran --version)
#          echo $(gcc --version)

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.3
        if: >-
          ( ! contains(matrix.buildplat[2], 'arm64' ) )
        # Build all wheels here, apart from macosx_arm64, linux_aarch64
        # cibuildwheel is currently unable to pass configuration flags to
        # CIBW_BUILD_FRONTEND https://github.com/pypa/cibuildwheel/issues/1227
        # (pip/build). Cross compilation with meson requires an initial
        # configuration step to create a build directory. The subsequent wheel
        # build then needs to use that directory. This can be done with pip
        # using a command like:
        # python -m pip wheel --config-settings builddir=build .
        env:
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}*
          CIBW_ARCHS: ${{ matrix.buildplat[2] }}
          CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS

          # MACOS_DEPLOYMENT_TARGET is set because of
          # https://github.com/pypa/cibuildwheel/issues/1419. Once that
          # is closed and meson-python==0.13 is available, then
          # that environment variable can be removed.
          CIBW_ENVIRONMENT_MACOS: >
            CC=clang
            MACOSX_DEPLOYMENT_TARGET=10.9
            MACOS_DEPLOYMENT_TARGET=10.9
            _PYTHON_HOST_PLATFORM=macosx-10.9-x86_64
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_sdist:
    runs-on: ubuntu-latest
    name: Build Source Distribution
    needs: [build_wheels]
    steps:
      - name: Checkout scikit-misc
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.8

      - name: Install requirements
        run:
          pip install -r requirements/build.txt

      - name: Build
        run: |
          make sdist

      - name: Upload Source dist
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: "build/meson-dist/"

  release:
    runs-on: ubuntu-latest
    name: Upload Release to PyPI
    needs: [build_wheels, build_sdist, parse_commit_info]
    if: contains(needs.parse_commit_info.outputs.can_release, 'Yes')
    steps:
      - name: Checkout scikit-misc
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.8

      - name: Install Release Requirements
        run: |
          pip install -r requirements/release.txt

      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Publish to PyPI
        run: |
          ls -la ${{ github.workspace }}/dist

          # publish wheels first so that there is no window where users
          # may accidentally install an sdist instead of a wheel
          twine upload ${{ github.workspace }}/dist/*.whl
          twine upload ${{ github.workspace }}/dist/*.tar.gz
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
